# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: "azure-logic-app-deploy"
- name: vResourceManagerConnection
  value: $[variables.ResourceManagerConnection]
- name: vSubscriptionName
  value: $[variables.SubscriptionName]
- name: vLocation
  value: $[variables.Location]

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "vResourceManagerConnection= $(vResourceManagerConnection)"
    echo "vSubscriptionName= $(vSubscriptionName)"
    echo "Location= $(vLocation)"
  displayName: 'Log variable values'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: $(ResourceManagerConnection)
    subscriptionName: $(SubscriptionName)
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureLogicApp'
    location: $(Location)
    templateLocation: 'Linked artifact'
    csmFile: '**/LogicApp.json'
    csmParametersFile: '**/LogicApp.parameters.json'
    deploymentMode: 'Incremental'