# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  Res_Mgr_Con: $(ResourceManagerConnection)
  Subs_Name: $(SubscriptionId)
  Loc: $(Location)

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: $(Res_Mgr_Con)
    subscriptionName: $(Subs_Name)
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureLogicApp'
    location: $(Loc)
    templateLocation: 'Linked artifact'
    csmFile: '**/LogicApp.json'
    csmParametersFile: '**/LogicApp.parameters.json'
    deploymentMode: 'Incremental'