# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- group: azure-logic-app-deploy
- name: vgsResourceManagerConnection
  value: $[variables.ResourceManagerConnection]
- name: vgsSubscriptionName
  value: $[variables.SubscriptionName]
- name: vgsLocation
  value: $[variables.Location]

trigger:
- master

stages:
- stage: 'HardCoded'
  displayName: 'DeployHardCoded'
  jobs:
  - deployment: 'Deploy Hardcoded'
    displayName: 'Deploy Hardcoded'
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    environment: Development
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: 'Pluralsight (d6d0fd8c-aab6-4713-b2f1-c9a0375d687d)'
              subscriptionName: 'd6d0fd8c-aab6-4713-b2f1-c9a0375d687d'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'AzureLogicApp'
              location: 'UK South'
              templateLocation: 'Linked artifact'
              csmFile: 'LogicApp.json'
              csmParametersFile: 'LogicApp.parameters.json'
              deploymentMode: 'Incremental'

- stage: RegularPV
  displayName: DeployRegularPV
  jobs:
  - deployment: 'Deploy Regular PV'
    displayName: 'Deploy Regular PV'
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    environment: Development
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: $(PVConnectedServiceName)
              subscriptionName: $(PVSubscriptionId)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(PVResourceGroup)
              location: $(PVLocation)
              templateLocation: 'Linked artifact'
              csmFile: '**/LogicApp.json'
              csmParametersFile: '**/LogicApp.parameters.json'
              deploymentMode: 'Incremental'

- stage: SecretPV
  displayName: DeploySecretPV
  jobs:
  - deployment: 'Deploy Secret PV'
    displayName: 'Deploy Secret PV'
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    environment: Development
    strategy: 
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: $(PVSConnectedServiceName)
              subscriptionName: $(PVSSubscriptionId)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(PVSResourceGroup)
              location: $(PVSLocation)
              templateLocation: 'Linked artifact'
              csmFile: '**/LogicApp.json'
              csmParametersFile: '**/LogicApp.parameters.json'
              deploymentMode: 'Incremental'
