# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: 'HardcodedJobStage'
  displayName: 'HardcodedJobStage'
  jobs:
  - job: 'HardcodedJob'
    displayName: HardcodedJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
          deploymentScope: 'Resource Group'
          ConnectedServiceName: 'pssub-azlogicapprg'
          subscriptionName: 'd6d0fd8c-aab6-4713-b2f1-c9a0375d687d'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'AzureLogicApp'
          location: 'UK South'
          templateLocation: 'Linked artifact'
          csmFile: '**/LogicApp.json'
          csmParametersFile: '**/LogicApp.parameters.json'
          deploymentMode: 'Incremental'
    
    - task: CopyFiles@2
      inputs:
        Contents: $(Build.SourcesDirectory)/AzureLogicApp/**/*.json
        targetFolder: $(Build.ArtifactStagingDirectory)
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: armtemplate

- stage: 'HardCodedDeployJobStage'
  displayName: 'HardCodedDeployJobStage'
  jobs:
  - deployment: 'HardCodedDeployJob'
    displayName: HardCodedDeployJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    environment: development
    strategy:
     runOnce:
       deploy:
         steps:
         - task: DownloadPipelineArtifact@2
           inputs:
             artifact: armtemplate

         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
             deploymentScope: 'Resource Group'
             ConnectedServiceName: 'pssub-azlogicapprg'
             subscriptionName: 'd6d0fd8c-aab6-4713-b2f1-c9a0375d687d'
             action: 'Create Or Update Resource Group'
             resourceGroupName: 'AzureLogicApp'
             location: 'UK South'
             templateLocation: 'Linked artifact'
             csmFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.json
             csmParametersFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.parameters.json
             deploymentMode: 'Incremental'

- stage: PVJobStage
  displayName: PVJobStage
  jobs:
  - job: PVJob
    displayName: PVJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: $(PVConnectedServiceName)
        subscriptionName: $(PVSubscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(PVResourceGroup)
        location: $(PVLocation)
        templateLocation: 'Linked artifact'
        csmFile: '**/LogicApp.json'
        csmParametersFile: '**/LogicApp.parameters.json'
        deploymentMode: 'Incremental'


- stage: PVDeployJobStage
  displayName: PVDeployJobStage
  jobs:
  - deployment: PVDeployJob
    displayName: PVDeployJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    environment: development
    strategy:
     runOnce:
       deploy:
         steps:
         - task: DownloadPipelineArtifact@2
           inputs:
             artifact: armtemplate

         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
             deploymentScope: 'Resource Group'
             ConnectedServiceName: $(PVConnectedServiceName)
             subscriptionName: $(PVSubscriptionId)
             action: 'Create Or Update Resource Group'
             resourceGroupName: $(PVResourceGroup)
             location: $(PVLocation)
             templateLocation: 'Linked artifact'
             csmFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.json
             csmParametersFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.parameters.json
             deploymentMode: 'Incremental'

- stage: PrintSecrets
  jobs:
  - job:
    steps:
    - task: CmdLine@2
      displayName: 'Print Secrets to file'
      inputs:
        script: 'echo "$(PVSConnectedServiceName) $(PVSSubscriptionId) $(PVSLocation)" > $(System.DefaultWorkingDirectory)/pipelinesecrets.txt'

    - task: CopyFiles@2
      inputs:
        Contents: $(System.DefaultWorkingDirectory)/pipelinesecrets.txt
        targetFolder: $(Build.ArtifactStagingDirectory)/secrets
  
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/secrets
        artifactName: secretdrop
