

variables:
- group: azure-logic-app-deploy

stages:
- stage: 'PipelineArtifactPublishStage'
  displayName: 'PipelineArtifactPublishStage'
  jobs:
  - job: 'PipelineArtifactPublishJob'
    displayName: PipelineArtifactPublishJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    steps:
    - task: CopyFiles@2
      inputs:
        Contents: $(Build.SourcesDirectory)/AzureLogicApp/**/*.json
        targetFolder: $(Build.ArtifactStagingDirectory)
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: armtemplate
        
- stage: PVSDeployJobStage
  displayName: PVSDeployJobStage
  jobs:
  - deployment: PVSDeployJob
    displayName: PVSDeployJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    environment: development
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: armtemplate

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: $(PVConnectedServiceName)
              KeyVaultName: 'send-grid-emailer-vault'
              SecretsFilter: '*'
              RunAsPreJob: true
    
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              ConnectedServiceName: $(ResourceManagerConnection)
              subscriptionName: $(SubscriptionName)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(ResourceGroup)
              location: $(Location)
              templateLocation: 'Linked artifact'
              csmFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.json
              csmParametersFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.parameters.json
              deploymentMode: 'Incremental'
