
stages:
- stage: PVJobStage
  displayName: PVJobStage
  jobs:
  - job: PVJob
    displayName: PVJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        ConnectedServiceName: $(PVConnectedServiceName)
        subscriptionName: $(PVSubscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(PVResourceGroup)
        location: $(PVLocation)
        templateLocation: 'Linked artifact'
        csmFile: '**/LogicApp.json'
        csmParametersFile: '**/LogicApp.parameters.json'
        deploymentMode: 'Incremental'