
stages:
- stage: PrintSecrets
  jobs:
  - job:
    steps:
    - task: CmdLine@2
      displayName: 'Print Secrets to file'
      inputs:
        script: 'echo "$(PVSConnectedServiceName) $(PVSSubscriptionId) $(PVSLocation)" > $(System.DefaultWorkingDirectory)/pipelinesecrets.txt'

    - task: CopyFiles@2
      inputs:
        Contents: $(System.DefaultWorkingDirectory)/pipelinesecrets.txt
        targetFolder: $(Build.ArtifactStagingDirectory)/secrets
  
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)/secrets
        artifactName: secretdrop

