trigger: none
pr: none

stages:
- stage: 'PipelineArtifactPublishStage'
  displayName: 'PipelineArtifactPublishStage'
  jobs:
  - job: 'PipelineArtifactPublishJob'
    displayName: PipelineArtifactPublishJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    steps:
    - task: CopyFiles@2
      inputs:
        Contents: $(Build.SourcesDirectory)/AzureLogicApp/**/*.json
        targetFolder: $(Build.ArtifactStagingDirectory)
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(Build.ArtifactStagingDirectory)
        artifactName: armtemplate
        
- stage: PVDeployJobStage
  displayName: PVDeployJobStage
  jobs:
  - deployment: PVDeployJob
    displayName: PVDeployJob
    pool:
      vmImage: ubuntu-latest
      workspace:
        clean: all
    environment: development
    strategy:
     runOnce:
       deploy:
         steps:
         - task: DownloadPipelineArtifact@2
           inputs:
             artifact: armtemplate

         - task: AzureResourceManagerTemplateDeployment@3
           inputs:
             deploymentScope: 'Resource Group'
             ConnectedServiceName: $(PVConnectedServiceName)
             subscriptionName: $(PVSubscriptionId)
             action: 'Create Or Update Resource Group'
             resourceGroupName: $(PVResourceGroup)
             location: $(PVLocation)
             templateLocation: 'Linked artifact'
             csmFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.json
             csmParametersFile: $(Pipeline.Workspace)/armtemplate/**/LogicApp.parameters.json
             deploymentMode: 'Incremental'